# Generated by Django 4.1.3 on 2022-12-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, default='photo-placeholder.png', upload_to='authors/'),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='book-placeholder.jpeg', upload_to='books/'),
        ),
        migrations.AddField(
            model_name='genre',
            name='image',
            field=models.ImageField(blank=True, default='image-placeholder.jpeg', upload_to='genres/'),
        ),
    ]
